create table exercises (
    id bigint generated by default as identity,
    repetitions integer not null,
    series integer not null,
    title text not null,
    primary key (id)
);

create table workout_exercises (
    workout_id bigint not null,
    exercise_id bigint not null,
    primary key (workout_id, exercise_id)
);

create table workouts (
    id bigint generated by default as identity,
    completed boolean not null,
    created_at timestamp(6) not null,
    schedule_type varchar(7) not null,
    scheduled_date timestamp(6) not null,
    title text not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

alter table if exists workout_exercises 
    add constraint FK3bn8puhdk29j682es5643p60c 
    foreign key (exercise_id) 
    references exercises;

alter table if exists workout_exercises 
    add constraint FKd2ychryarm8gp13672lojwr78 
    foreign key (workout_id) 
    references workouts;